# - x - x - x - x - x - x - x - x - x - x - x - x - x - x - #
#                                                           #
#   This file was created by: Alberto Palomo Alonso         #
# Universidad de Alcalá - Escuela Politécnica Superior      #
#                                                           #
# - x - x - x - x - x - x - x - x - x - x - x - x - x - x - #
# Import statements:
KERAS_LIST_LAYERS = ['Dense',
                     'Activation',
                     'Embedding',
                     'Masking',
                     'Lambda',
                     '',
                     'Conv1D',
                     'Conv2D',
                     'Conv3D',
                     'SeparableConv1D',
                     'SeparableConv2D',
                     'DepthwiseConv2D',
                     'Conv1DTranspose',
                     'Conv2DTranspose',
                     'Conv3DTranspose',
                     '',
                     'MaxPooling1D',
                     'MaxPooling2D',
                     'MaxPooling3D',
                     'AveragePooling1D',
                     'AveragePooling2D',
                     'AveragePooling3D',
                     'GlobalMaxPooling1D',
                     'GlobalMaxPooling2D',
                     'GlobalMaxPooling3D',
                     'GlobalAveragePooling1D',
                     'GlobalAveragePooling2D',
                     'GlobalAveragePooling3D',
                     '',
                     'LSTM',
                     'GRU',
                     'SimpleRNN',
                     'RNN',
                     'TimeDistributed',
                     'Bidirectional',
                     'ConvLSTM1D',
                     'ConvLSTM2D',
                     'ConvLSTM3D',
                     '',
                     'TextVectorization',
                     'Normalization',
                     'Discretization',
                     'CategoryEncoding',
                     'Hashing',
                     'StringLookup',
                     'IntegerLookup',
                     'Resizing',
                     'Rescaling',
                     'CenterCrop',
                     'RandomCrop',
                     'RandomFlip',
                     'RandomTranslation',
                     'RandomRotation',
                     'RandomZoom',
                     'RandomHeight',
                     'RandomWidth',
                     'RandomContrast',
                     'RandomBrightness',
                     '',
                     'Dropout',
                     'SpatialDropout1D',
                     'SpatialDropout2D',
                     'SpatialDropout3D',
                     'GaussianDropout',
                     'GaussianNoise',
                     'ActivityRegularization',
                     'AlphaDropout',
                     '',
                     'BatchNormalization',
                     'LayerNormalization',
                     'UnitNormalization',
                     '',
                     'MultiHeadAttention',
                     'Attention',
                     'AdditiveAttention',
                     '',
                     'Reshape',
                     'Flatten',
                     'RepeatVector',
                     'Permute',
                     'Cropping1D',
                     'Cropping2D',
                     'Cropping3D',
                     'UpSampling1D',
                     'UpSampling2D',
                     'UpSampling3D',
                     'ZeroPadding1D',
                     'ZeroPadding2D',
                     'ZeroPadding3D',
                     '',
                     'Concatenate',
                     'Average',
                     'Maximum',
                     'Minimum',
                     'Add',
                     'Subtract',
                     'Multiply',
                     'Dot',
                     '',
                     'LocallyConnected1D',
                     'LocallyConnected2D',
                     '',
                     'ReLU',
                     'Softmax',
                     'LeakyReLU',
                     'PReLU',
                     'ELU',
                     'ThresholdedReLU',
                     ''
                     ]
PREBUILT_LAYERS = [
    'open_pipeline',
    'close_pipeline',
    ''
    '(!) RandomForest',
    '(!) DecisionTree',
    '(!) Pbmm',
    ''
]

KERAS_LOSSES = [
            'kld', 'mean_absolute_error', 'mean_absolute_percentage_error', 'mean_squared_error',
            'mean_squared_logarithmic_error', 'binary_crossentropy', 'binary_focal_crossentropy',
            'categorical_crossentropy', 'categorical_hinge', 'cosine_similarity', 'deserialize', 'get', 'hinge',
            'huber_loss', 'log_cosh', 'poisson', 'serialize', 'sparse_categorical_crossentropy', 'squared_hinge', ''
        ]

PREBUILT_LOSSES = ['(!) window_diff']

KERAS_OPTIMIZERS = ['adadelta', 'adam', 'RMSprop', 'sgd', 'nadam', 'adamax', 'adagrad', 'ftlr']

PREBUILT_OPTIMIZERS = ['(!)']
# - x - x - x - x - x - x - x - x - x - x - x - x - x - x - #
#                        END OF FILE                        #
# - x - x - x - x - x - x - x - x - x - x - x - x - x - x - #
